### ISSUE TITLE
"Broken Link" Is Not Broken

### ISSUE THREAD

**Issue by bieber** [sterling-archermedes/sterling-archermedes.github.io#1]
Lines 607 and 608 of index.html read
```html
     <p> There is a link for this one but it's broken. We will have to
      take the word of the renowned news source on that one.
```

Implying that the journalists in question have made up this source from whole cloth.  In fact, the link in question is very much not broken, you can see it live on Stallman's website right here: https://stallman.org/cgi-bin/showpage.cgi?path=/archives/2006-mar-jun.html&term=DHS&type=norm&case=0

In particular, this is the entry that the article was referencing:

> 06 April 2006 ( DHS spokesman sex scandal? )
Many Americans would see a scandal in the DHS spokesman who has been arrested for proposing sex to a 14-year-old girl through the Internet.
>
> I too see a scandal, but not the same one. I think the scandal is that this man is going to face a prison sentence when he has not done wrong to anyone.
>
> Sometimes adults are in a position of power over teenagers (or even children) and use that power to pressure them into sex. That is wrong because it is coercion. Sometimes they manipulate or trick inexperienced people into sex they didn't want. That's not right because it is not honest.
>
> But this man seems to have done none of those things. He was chatting with a stranger, clearly not dependent on him in any way. The report gives no reason to think he was pressuring or tricking her. For all we can tell, he was making an honest request. Supposing his interlocutor had been a real girl, if she had not wanted to have sex with him, she would have had no trouble saying "no thanks". And supposing she had voluntarily had sex with him, presuming that they used a condom and suitable contraception, it would have done no harm to either of them.

I trust that, given this new information, you'll remove the claim that the link is broken from your review and also remove your claim that Stallman's reference to "voluntary pedophilia" couldn't have been about adults and children, given that here he is directly defending an adult attempting to sleep with a fourteen year old.

**Comment by sterling-archermedes** [comment]
Corrected. It now also includes a post where he says he changed his mind.
