### ISSUE TITLE
rms reaction to "I use vi"

### ISSUE THREAD

**Issue by ltworf** [sterling-archermedes/sterling-archermedes.github.io#2]
Don't know if this bugreport is appropriate.

Anyway ~10years ago rms came to give a speech in my university, and while he was doing saint ignicious a friend of mine told him "Forgive me father because I use vi", to which he replied "If it is a free implementation of vi, there is no sin."

So from what I can tell, at that point, he was more concerned about free software than adoption of his pet project in particular.

**Comment by sterling-archermedes** [comment]
Yeah, the "problematic" emacs joke was a gross mis-characterization of an innocent and well understood thing.
